# Generated by Django 5.2.8 on 2025-12-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
