# Generated by Django 5.2.8 on 2025-12-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staff_check_in_staff_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Late', 'Late')], default='Inactive', max_length=10),
        ),
    ]
