# Generated by Django 5.2.9 on 2025-12-06 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleMeet',
            fields=[
                ('meet_id', models.AutoField(primary_key=True, serialize=False)),
                ('meet_time', models.DateTimeField()),
                ('meet_title', models.CharField(max_length=255)),
                ('meet_description', models.TextField(blank=True, null=True)),
                ('meet_link', models.CharField(blank=True, max_length=500, null=True)),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='accounts.register')),
            ],
        ),
    ]
