# Generated by Django 5.2.9 on 2025-12-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_googlemeet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleMeet',
        ),
    ]
