# Generated by Django 5.2.9 on 2025-12-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_googlemeet'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleMeet',
            fields=[
                ('meet_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=100)),
                ('meet_time', models.DateTimeField()),
                ('meet_title', models.CharField(max_length=255)),
                ('meet_description', models.TextField(blank=True, null=True)),
                ('meet_link', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
