# Generated by Django 5.2.9 on 2025-12-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_googlemeet'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlemeet',
            name='meet_time_display',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
