# Generated by Django 5.2.9 on 2025-12-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_googlemeet_meet_time_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlemeet',
            name='meet_time_str',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
