# Generated by Django 5.2.9 on 2025-12-06 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_googlemeet_meet_time_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlemeet',
            name='meet_time_display',
        ),
        migrations.RemoveField(
            model_name='googlemeet',
            name='meet_time_str',
        ),
    ]
