# Generated by Django 5.2.9 on 2025-12-08 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_workschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('emotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('emotion_type', models.CharField(choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Neutral', 'Neutral'), ('Angry', 'Angry'), ('Tired', 'Tired'), ('Focused', 'Focused')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotions', to='accounts.staff')),
            ],
        ),
    ]
