# Generated by Django 5.2.9 on 2025-12-08 22:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_emotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_addressed', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='accounts.staff')),
            ],
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_problem', models.TextField()),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('proposed_action', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='accounts.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Productivity',
            fields=[
                ('productvity_id', models.AutoField(primary_key=True, serialize=False)),
                ('score_percent', models.PositiveSmallIntegerField(help_text='0-100')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivities', to='accounts.staff')),
            ],
        ),
    ]
