# Generated by Django 5.2.9 on 2025-12-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_feedback_issuereport_productivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='is_addressed',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
