# Generated by Django 5.2.9 on 2025-12-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_feedback_is_addressed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='date',
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
