# Generated by Django 5.2.9 on 2026-01-31 15:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_workschedule_date_alter_workschedule_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productivity',
            old_name='productvity_id',
            new_name='productivity_id',
        ),
        migrations.RemoveField(
            model_name='productivity',
            name='date',
        ),
        migrations.RemoveField(
            model_name='productivity',
            name='score_percent',
        ),
        migrations.AddField(
            model_name='productivity',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productivity',
            name='keystroke',
            field=models.IntegerField(default=0, help_text='Total number of keystrokes'),
        ),
        migrations.AddField(
            model_name='productivity',
            name='mouse_moves',
            field=models.IntegerField(default=0, help_text='Total mouse movements or clicks'),
        ),
        migrations.AddField(
            model_name='productivity',
            name='productivity_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated productivity score', max_digits=6),
        ),
        migrations.AlterField(
            model_name='productivity',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity_records', to='accounts.staff'),
        ),
    ]
